name: pnpm-verify
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-version:
        type: string
        required: false
        default: '[16, 18, 20]'
      pnpm-version:
        type: string
        required: false
        default: 8.14.1
      codecov-flags:
        type: string
        required: false
jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{ fromJson(inputs.node-version) }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Verify (Linux)
        run: xvfb-run -a pnpm verify
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Verify (Windows/Mac)
        run: pnpm verify
        if: ${{ matrix.os != 'ubuntu-latest' }}

      - name: codecov
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 20
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ inputs.codecov-flags }}
