name: build-docs
on:
  workflow_call:
    inputs:
      pnpm-version:
        type: string
        required: false
      publish-dir:
        type: string
        required: false
        default: ./docs

jobs:
  publish-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install
      - run: pnpm build
      - run: pnpm build:doc
      - name: publish docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish-dir }}
